### ISSUE TITLE
Issue in mysql database assessment checks

### ISSUE THREAD

**Issue by akshaykotagal** [foospidy/DbDat#8]
Hi,
The database checks for mysql database is throwing errors.
Below is the console output:
```
Assessment: mysql database mysql on localhost with the user root and 38 queries.
Performing check: SHUTDOWN Privilege
Performing check: User Grants
Performing check: mysql Database Access
Performing check: RELOAD Privilege
Performing check: Safe Show Database
Performing check: Check General Log
Traceback (most recent call last):
  File "dbdat.py", line 277, in <module>
    scan.hacktheplanet()
  File "dbdat.py", line 128, in hacktheplanet
    result['result'] = c.do_check(self.config)
  File "/home/seconize/dbdat/DbDat/plugins/mysql/check_configuration_general_log.py", line 30, in do_check
    general_log_file = configuration.get('mysqld', 'general_log_file')
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigPars_er.NoSectionError: No section: 'mysqld'

```
I have tried to suppress the checks in `plugins/mysql/__init__.py` but other issues related to checks show up.
Can you please help me out debugging the above issue?

**Comment by sashank** [comment]
The issue was with lack of proper conf files , we could make it work , feel free to close it

**Comment by foospidy** [comment]
Ok, I'm glad you got it worked out, Thanks!

**Comment by kksoni** [comment]
I am getting error while assessment of POSTGRESQL

Traceback (most recent call last):
  File "dbdat.py", line 277, in <module>
    scan.hacktheplanet()
  File "dbdat.py", line 116, in hacktheplanet
    check = self.load_class('plugins.' + self.dbtype + '.' + database_check)
  File "dbdat.py", line 194, in load_class
    module     = __import__(name)
  File "/root/sa/db/DbDat/plugins/postgresql/__init__.py", line 1, in <module>
    from check_information_banner import *
ModuleNotFoundError: No module named 'check_information_banner'



I am using python3 & python2.7 by tried both python version.

but unable to do assessment .

Any help would be appriciable.
THanks
